/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/dragon-ring.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function DragonRing(props, scale, color) {
  const { nodes, materials } = useGLTF(
    "./public/model/dragon-ring.gltf"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Node_#0"].geometry}
        material={nodes["Node_#0"].material}
      />
    </group>
  );
}

useGLTF.preload("./public/model/dragon-ring.gltf");
